version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms64m -Xmx128m -XX:+UseContainerSupport"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_ISSUER: ${APP_JWT_ISSUER}
      APP_JWT_EXPIRATION_SECONDS: ${APP_JWT_EXPIRATION_SECONDS}
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: "0.3"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    image: myapp-frontend:staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
      - BACKEND_URL=${BACKEND_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    deploy:
      resources:
        limits:
          memory: 80M
          cpus: "0.2"
    depends_on:
      - postgres
      - server
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/odontolog.tech:/etc/letsencrypt/live/odontolog.tech:ro
      - /etc/letsencrypt/archive/odontolog.tech:/etc/letsencrypt/archive/odontolog.tech:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
      - frontend
    networks:
      - app-network
      - proxy
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: "0.15"

volumes:
  postgres_data:

networks:
  proxy:
    driver: bridge
  app-network:
    internal: true
