CREATE TABLE anamnese_activities
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type        VARCHAR(255),
    actor_id    UUID,
    anamnese_id BIGINT,
    description VARCHAR(255),
    metadata    JSONB,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_anamnese_activities PRIMARY KEY (id)
);

CREATE TABLE anamneses
(
    id    BIGINT NOT NULL,
    notes VARCHAR(255),
    CONSTRAINT pk_anamneses PRIMARY KEY (id)
);

CREATE TABLE patient_conditions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    anamnese_id   BIGINT                                  NOT NULL,
    condition     VARCHAR(255),
    notes         VARCHAR(255),
    category      VARCHAR(255),
    has_condition BOOLEAN,
    CONSTRAINT pk_patient_conditions PRIMARY KEY (id)
);

ALTER TABLE anamneses
    ADD CONSTRAINT FK_ANAMNESES_ON_ID FOREIGN KEY (id) REFERENCES patients (id);

ALTER TABLE anamnese_activities
    ADD CONSTRAINT FK_ANAMNESE_ACTIVITIES_ON_ACTOR FOREIGN KEY (actor_id) REFERENCES users (id);

ALTER TABLE anamnese_activities
    ADD CONSTRAINT FK_ANAMNESE_ACTIVITIES_ON_ANAMNESE FOREIGN KEY (anamnese_id) REFERENCES anamneses (id);

ALTER TABLE patient_conditions
    ADD CONSTRAINT FK_PATIENT_CONDITIONS_ON_ANAMNESE FOREIGN KEY (anamnese_id) REFERENCES anamneses (id);