CREATE TABLE patient_permissions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id  UUID NOT NULL,
    patient_id  BIGINT NOT NULL,
    granted_at  TIMESTAMP WITHOUT TIME ZONE,
    revoked_at  TIMESTAMP WITHOUT TIME ZONE,
    active      BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT pk_patient_permissions PRIMARY KEY (id)
);

ALTER TABLE patient_permissions
    ADD CONSTRAINT FK_PATIENT_PERM_ON_STUDENT FOREIGN KEY (student_id) REFERENCES users (id);

ALTER TABLE patient_permissions
    ADD CONSTRAINT FK_PATIENT_PERM_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patients (id);
