export const studySectors = [
  'Dentística',
  'Endodontia',
  'Cirurgia oral',
  'Periodontia',
  'Ortodontia',
  'Cirurgia',
];

export const teeth = [
  'Todos',
  'Gengiva',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '31',
  '32',
  '33',
  '34',
  '35',
  '36',
  '37',
  '38',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
  '48',
];

export const maritalStatus = [
  { value: 'SINGLE', label: 'Solteiro' },
  { value: 'MARRIED', label: 'Casado' },
  { value: 'DIVORCED', label: 'Divorciado' },
  { value: 'WIDOWED', label: 'Viúvo' },
  { value: 'CIVIL_UNION', label: 'União Estável' },
];

export const sex = [
  { value: 'FEMALE', label: 'Feminino' },
  { value: 'MALE', label: 'Masculino' },
  { value: 'OTHER', label: 'Outro' },
];

export const ethnicity = [
  { value: 'WHITE', label: 'Branco' },
  { value: 'BLACK', label: 'Preto' },
  { value: 'BROWN', label: 'Pardo' },
  { value: 'YELLOW', label: 'Amarelo' },
  { value: 'INDIGENOUS', label: 'Indígena' },
  { value: 'OTHER', label: 'Outro' },
];

export const procedureNames = [
  'Acesso a Polpa Dentária e Medicação (por Dente)',
  'Aparelho Fixo Bilateral p/ Fechamento de Diastema',
  'Aparelho Ortodôntico Removível',
  'Apicetomia com ou sem Obturação Retrógrada',
  'Aplicação de Cariostático (por dente)',
  'Aplicação de Selante (por Dente)',
  'Aplicação Tópica de Flúor (Individual por Sessão)',
  'Aprofundamento de Vestíbulo (por Sextante)',
  'Alveolotomia / Alveolectomia (por Arco Dentário)',
  'Capeamento Pulpar',
  'Colocação de Placa de Mordida',
  'Coroa de Aço e Policarboxilato',
  'Coroa Provisória',
  'Correção de Bridas Musculares',
  'Correção de Irregularidades de Rebordo Alveolar',
  'Correção de Tuberosidade Do Maxilar',
  'Curativo de Demora c/ ou s/ Preparo Químico Mecânico',
  'Curetagem Periapical',
  'Enxerto Gengival',
  'Exerto Ósseo de Área Doadora Intrabucal',
  'Evidenciação de Placa Bacteriana',
  'Excisão de Cálculo de Glândula Salivar',
  'Excisão de Glândular Submandibular / Submaxilar / Sublingual',
  'Excisão de Rânula ou Fenômeno de Retenção Salivar',
  'Excisão e Sutura de Lesão na Boca',
  'Exodontia de Dente Decíduo',
  'Exodontia de Dente Permanente',
  'Exodontia Múltipla Com Alveoloplastia por Sextante',
  'Gengivectomia (por Sextante)',
  'Gengivoplastia (por Sextante)',
  'Glossorafia',
  'Implante Osteointegrado Extra-Oral Bucomaxilofacial',
  'Instalação e Adaptação de Prótese Dentária',
  'Mantenedor de Espaço',
  'Manutenção / Conserto de Aparelhos Ortodônticos',
  'Marsupialização de Cistos e Pseudocistos',
  'Moldagem Dento-Gengival p/ Construção de Prótese Dentária',
  'Obturação de Dente Decíduo',
  'Obturação em Dente Permanente Unirradicular',
  'Obturação em Dente Permanente Bi-Radicular',
  'Obturação em Dente Permanente c/ Três ou Mais Raízes',
  'Placa de Contenção',
  'Placa Oclusal',
  'Plano Inclinado',
  'Primeira Consulta Odontológica Programática',
  'Prótese Parcial Mandibular Removível',
  'Prótese Parcial Maxilar Removível',
  'Prótese Temporária',
  'Prótese Total Mandibular',
  'Prótese Total Maxilar',
  'Próteses Coronárias / Intra-Radiculares Fixas / Adesivas (por Elemento)',
  'Pulpotomia Dentária',
  'Radiografia Oclusal',
  'Radiografia Peri-Apical / Interproximal (Bite-Wing)',
  'Raspagem Corono-Radicular (por Sextante)',
  'Raspagem, Alisamento e Polimento Supragengivais (por Sextante)',
  'Raspagem, Alisamento Subgengivais (por Sextante)',
  'Reconstrução de Sulco Gengivo-Labial',
  'Reconstrução Parcial Do Lábio Traumatizado',
  'Redução Incruenta de Luxação Temporo-Mandibular',
  'Reembasamento e Conserto de Prótese Dentária',
  'Reimplante e Transplante Dental (por Elemento)',
  'Remoção de Cisto',
  'Remoção de Corpo Estranho Da Região Bucomaxilofacial',
  'Remoção de Dente Retido (Incluso / Impactado)',
  'Remoção de Foco Residual',
  'Remoção de Torus e Exostoses',
  'Restauração de Dente Decíduo',
  'Restauração de Dente Permanente Anterior',
  'Restauração de Dente Permanente Posterior',
  'Retirada de Material de Síntese Óssea / Dentária',
  'Retratamento Endodôntico em Dente Permanente Unirradicular',
  'Retratamento Endodôntico em Dente Permanente Bi-Radicular',
  'Retratamento Endodôntico em Dente Permanente c/ 3 ou Mais Raízes',
  'Selamento de Fístula Cutânea Odontogênica',
  'Selamento de Perfuração Radicular',
  'Selamento Provisório de Cavidade Dentária',
  'Sinusotomia Maxilar Unilaterial',
  'Tratamento Cirúrgico de Fístula Intra / Extra Oral',
  'Tratamento Cirúrgico de Hemorragia Buco-Dental',
  'Tratamento Cirúrgico Para Tracionamento Dental',
  'Tratamento Cirúrgico Periodontal (por Sextante)',
  'Tratamento de Alveolite',
  'Tratamento de Nevralgias Faciais',
  'Tratamento Emergencial p/ Redução de Fratura Alveolo-Dentária',
  'Ulotomia / Ulectomia',
];
