name: Deploy to DigitalOcean Droplet

on:
  pull_request:
    branches: [ "**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify files exist
        run: |
          echo "Current path: $(pwd)"
          ls -lah

      - name: Copy project files to Droplet
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "docker-compose.prod.yml nginx.conf frontend server"
          target: odontolog

      - name: Deploy to DigitalOcean Droplet via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            set -e
            cd odontolog
            echo "Building and starting containers..."
            docker compose -f docker-compose.prod.yml build
            docker compose -f docker-compose.prod.yml up -d --build
            docker system prune -f