name: CI (Nextjs Frontend)

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

env:
  NODE_VERSION: "22"

jobs:
  frontend:
    name: Frontend (ESLint + Prettier)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
          
      - run: npm ci
      - run: npm run lint
      - run: npm run format-check
      - run: npm run build
